import { useMemo, useState } from 'react';
import { ScrollView, StyleSheet, View } from 'react-native';
import { useForm } from 'react-hook-form';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { Chip, IconButton, RadioButton, Text, useTheme } from 'react-native-paper';
import { AnimatedButton } from '../components/AnimatedButton';
import { CalculationBreakdown } from '../components/CalculationBreakdown';
import { FadeInCard } from '../components/FadeInCard';
import { NumberField } from '../components/Field';
import { RateSkeleton } from '../components/RateSkeleton';
import { PURITY_LABELS } from '../constants';
import { useRates } from '../hooks/useRates';
import { storage } from '../storage/storage';
import { CalculationResult, Metal, Purity } from '../types';
import { calculateJewellery, dateTime, money } from '../utils/calculation';

interface FormValues { weight: string; makingPercent: string; hallmark: string; stone: string; rhodium: string; }
const defaultValues: FormValues = { weight: '', makingPercent: '', hallmark: '0', stone: '0', rhodium: '0' };
export function HomeScreen({ autoRefresh }: { autoRefresh: boolean }) { const theme = useTheme(); const [metal, setMetal] = useState<Metal>('gold'); const [purity, setPurity] = useState<Purity>('gold22'); const [result, setResult] = useState<CalculationResult>(); const { data: rates, isLoading, refetch } = useRates(autoRefresh); const { control, handleSubmit, reset } = useForm<FormValues>({ defaultValues });
  const choices: Purity[] = metal === 'gold' ? ['gold22', 'gold18'] : ['silver90', 'silver925'];
  const selectMetal = (next: Metal) => { setMetal(next); setPurity(next === 'gold' ? 'gold22' : 'silver90'); setResult(undefined); };
  const onCalculate = handleSubmit(async values => { const weight = Number(values.weight); if (!weight || weight <= 0 || !rates) return; const next = calculateJewellery({ metal, purity, weight, makingPercent: Number(values.makingPercent || 0), hallmark: Number(values.hallmark || 0), stone: Number(values.stone || 0), rhodium: Number(values.rhodium || 0), rate: rates[purity] }); setResult(next); const history = await storage.getHistory(); await storage.saveHistory([next, ...history].slice(0, 100)); });
  const rate = rates?.[purity]; const displayRate = rate ? (metal === 'gold' ? rate * 10 : rate * 1000) : undefined; const unit = metal === 'gold' ? '/10gm' : '/kg';
  return <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.hero}><View><Text variant="headlineSmall" style={styles.title}>Shraddha{`\n`}Jewellers</Text><Text variant="bodyMedium" style={styles.heroSub}>Jewellery Rate Calculator</Text><Text variant="bodySmall" style={styles.heroCaption}>A Dgonix solution</Text></View><View style={styles.heroIcon}><MaterialCommunityIcons name="diamond-stone" color="#3A0D1C" size={30}/></View></View>
    <FadeInCard style={styles.card}><View style={styles.cardPad}><Text variant="titleMedium">Select metal</Text><View style={styles.metalRow}>{(['gold', 'silver'] as Metal[]).map(item => <Chip key={item} selected={metal === item} onPress={() => selectMetal(item)} showSelectedCheck icon={item === 'gold' ? 'gold' : 'circle-outline'} style={styles.chip}>{item === 'gold' ? 'Gold' : 'Silver'}</Chip>)}</View><RadioButton.Group value={purity} onValueChange={v => { setPurity(v as Purity); setResult(undefined); }}>{choices.map(item => <RadioButton.Item key={item} value={item} label={PURITY_LABELS[item]} position="leading" style={styles.radio}/>)}</RadioButton.Group></View></FadeInCard>
    <FadeInCard style={styles.rateCard}><View style={styles.cardPad}>{isLoading ? <RateSkeleton/> : <><View style={styles.rateHeader}><View style={styles.rateContent}><Text variant="labelLarge">LIVE MARKET RATE</Text><Text variant="headlineSmall" numberOfLines={1} adjustsFontSizeToFit style={{ color: theme.colors.primary }}>{displayRate ? `${money(displayRate)} ${unit}` : 'Rate unavailable'}</Text><Text variant="bodySmall" numberOfLines={1}>{PURITY_LABELS[purity]} · live converted market price</Text></View><IconButton icon="refresh" mode="contained-tonal" size={20} onPress={() => refetch()} accessibilityLabel="Refresh market rates" /></View><Text variant="bodySmall" style={styles.updated}>{rates?.source === 'cache' ? 'Using cached prices · ' : rates?.source === 'fallback' ? 'Offline fallback prices · ' : ''}Last updated {rates ? dateTime(rates.updatedAt) : '—'}</Text></>}</View></FadeInCard>
    <FadeInCard style={styles.card}><View style={styles.cardPad}><Text variant="titleMedium" style={styles.sectionTitle}>Jewellery details</Text><NumberField control={control} name="weight" label="Weight (grams)" suffix="gm" /><NumberField control={control} name="makingPercent" label="Making Charges (%)" suffix="%" /><NumberField control={control} name="hallmark" label="Hallmark Charges (₹)" suffix="₹" /><NumberField control={control} name="stone" label="Stone Charges (₹)" suffix="₹" /><NumberField control={control} name="rhodium" label="Rhodium Charges (₹)" suffix="₹" /><View style={styles.actions}><AnimatedButton mode="contained" icon="calculator" onPress={onCalculate} style={styles.calculate}>Calculate</AnimatedButton><AnimatedButton mode="outlined" onPress={() => { reset(defaultValues); setResult(undefined); }}>Reset</AnimatedButton></View></View></FadeInCard>
    {result && <FadeInCard style={styles.card}><Text variant="titleMedium" style={styles.resultTitle}>Calculation summary</Text><CalculationBreakdown result={result}/></FadeInCard>}
  </ScrollView>; }
const styles = StyleSheet.create({ content: { padding: 16, gap: 14, paddingBottom: 32 }, hero: { minHeight: 106, padding: 18, borderRadius: 22, backgroundColor: '#3A0D1C', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', shadowColor: '#3A0D1C', shadowOpacity: .24, shadowRadius: 12, elevation: 5 }, title: { fontWeight: '800', color: '#FFFFFF' }, heroSub: { color: '#F2D29B', marginTop: 3 }, heroCaption: { color: '#F3E6D6', opacity: .72, marginTop: 4 }, heroIcon: { width: 58, height: 58, borderRadius: 18, backgroundColor: '#D8AB5F', justifyContent: 'center', alignItems: 'center', elevation: 4 }, card: { borderRadius: 16, overflow: 'hidden' }, rateCard: { borderRadius: 16, overflow: 'hidden', borderWidth: 1, borderColor: '#C9A22755' }, cardPad: { padding: 16 }, metalRow: { flexDirection: 'row', gap: 10, marginVertical: 10 }, chip: { flex: 1 }, radio: { paddingVertical: 1 }, rateHeader: { flexDirection: 'row', alignItems: 'center', gap: 4 }, rateContent: { flex: 1, minWidth: 0 }, updated: { marginTop: 14, opacity: .65 }, sectionTitle: { marginBottom: 15 }, actions: { flexDirection: 'row', gap: 10, justifyContent: 'flex-end', marginTop: 6 }, calculate: { flex: 1 }, resultTitle: { paddingHorizontal: 16, paddingTop: 16 } });
